/*
 * #%L
 * Bitrepository Reference Pillar
 * %%
 * Copyright (C) 2010 - 2012 The State and University Library, The Royal Library and The State Archives, Denmark
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 2.1 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Lesser Public License for more details.
 *
 * You should have received a copy of the GNU General Lesser Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/lgpl-2.1.html>.
 * #L%
 */
package org.bitrepository.pillar.messagehandling;

import org.bitrepository.bitrepositoryelements.AuditTrailEvent;
import org.bitrepository.bitrepositorymessages.GetAuditTrailsFinalResponse;
import org.bitrepository.bitrepositorymessages.GetAuditTrailsProgressResponse;
import org.bitrepository.bitrepositorymessages.GetAuditTrailsRequest;
import org.bitrepository.bitrepositorymessages.IdentifyContributorsForGetAuditTrailsRequest;
import org.bitrepository.bitrepositorymessages.IdentifyContributorsForGetAuditTrailsResponse;
import org.bitrepository.pillar.MockedPillarTest;
import org.bitrepository.pillar.messagefactories.GetAuditTrailsMessageFactory;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

import javax.xml.datatype.XMLGregorianCalendar;
import java.util.Date;

import static java.lang.System.currentTimeMillis;
import static java.math.BigInteger.ONE;
import static java.math.BigInteger.valueOf;
import static org.bitrepository.bitrepositoryelements.FileAction.CHECKSUM_CALCULATED;
import static org.bitrepository.bitrepositoryelements.FileAction.DELETE_FILE;
import static org.bitrepository.bitrepositoryelements.FileAction.FAILURE;
import static org.bitrepository.bitrepositoryelements.FileAction.FILE_MOVED;
import static org.bitrepository.bitrepositoryelements.FileAction.GET_CHECKSUMS;
import static org.bitrepository.bitrepositoryelements.FileAction.GET_FILE;
import static org.bitrepository.bitrepositoryelements.FileAction.GET_FILEID;
import static org.bitrepository.bitrepositoryelements.FileAction.INCONSISTENCY;
import static org.bitrepository.bitrepositoryelements.FileAction.INTEGRITY_CHECK;
import static org.bitrepository.bitrepositoryelements.FileAction.OTHER;
import static org.bitrepository.bitrepositoryelements.FileAction.PUT_FILE;
import static org.bitrepository.bitrepositoryelements.FileAction.REPLACE_FILE;
import static org.bitrepository.bitrepositoryelements.ResponseCode.IDENTIFICATION_POSITIVE;
import static org.bitrepository.bitrepositoryelements.ResponseCode.OPERATION_ACCEPTED_PROGRESS;
import static org.bitrepository.bitrepositoryelements.ResponseCode.OPERATION_COMPLETED;
import static org.bitrepository.common.utils.CalendarUtils.getFromMillis;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class GetAuditTrailsTest extends MockedPillarTest {
    private GetAuditTrailsMessageFactory msgFactory;

    @Override
    public void initializeCUT() {
        super.initializeCUT();
        msgFactory = new GetAuditTrailsMessageFactory(collectionID, settingsForTestClient);
    }

    @Test
    @Tag("regressiontest")
    @Tag("pillartest")
    public void checksumPillarGetAuditTrailsSuccessful() {
        addDescription("Tests the GetAuditTrails functionality of the pillar for the successful scenario, "
                + "where all audit trails are requested.");
        addStep("Set up constants and variables.", "Should not fail here!");
        String auditTrail = "";
        audits.addAuditEvent(collectionID, "fileid", "actor", "info", "auditTrail", OTHER,
                "operationID", "certificateID");

        addStep("Send the identification request", "A positive response should be generated by the pillar");
        IdentifyContributorsForGetAuditTrailsRequest identifyRequest =
                msgFactory.createIdentifyContributorsForGetAuditTrailsRequest(
                        auditTrail, getPillarID(), clientDestinationId);
        messageBus.sendMessage(identifyRequest);
        IdentifyContributorsForGetAuditTrailsResponse receivedIdentifyResponse = clientReceiver.waitForMessage(
                IdentifyContributorsForGetAuditTrailsResponse.class);
        assertEquals(collectionID, receivedIdentifyResponse.getCollectionID());
        assertEquals(identifyRequest.getCorrelationID(), receivedIdentifyResponse.getCorrelationID());
        assertEquals(settingsForCUT.getComponentID(), receivedIdentifyResponse.getFrom());
        assertEquals(identifyRequest.getReplyTo(), receivedIdentifyResponse.getDestination());
        assertEquals(IDENTIFICATION_POSITIVE, receivedIdentifyResponse.getResponseInfo().getResponseCode());

        addStep("Make and send the request for the actual GetAuditTrails operation",
                "Should be caught and handled by the pillar.");
        GetAuditTrailsRequest request = msgFactory.createGetAuditTrailsRequest(auditTrail, getComponentID(),
                identifyRequest.getCorrelationID(), null, getPillarID(), null, null, null, null, null,
                clientDestinationId, null, pillarDestinationId);
        messageBus.sendMessage(request);

        addStep("Receive and validate the progress response.", "Should be sent by the pillar.");
        GetAuditTrailsProgressResponse progressResponse = clientReceiver.waitForMessage(GetAuditTrailsProgressResponse.class);
        assertEquals(collectionID, progressResponse.getCollectionID());
        assertEquals(identifyRequest.getCorrelationID(), progressResponse.getCorrelationID());
        assertEquals(settingsForCUT.getComponentID(), progressResponse.getFrom());
        assertEquals(identifyRequest.getReplyTo(), receivedIdentifyResponse.getDestination());
        assertEquals(OPERATION_ACCEPTED_PROGRESS, progressResponse.getResponseInfo().getResponseCode());

        addStep("Receive and validate the final response", "Should be sent by the pillar.");
        GetAuditTrailsFinalResponse finalResponse = clientReceiver.waitForMessage(GetAuditTrailsFinalResponse.class);
        assertEquals(collectionID, receivedIdentifyResponse.getCollectionID());
        assertEquals(identifyRequest.getCorrelationID(), receivedIdentifyResponse.getCorrelationID());
        assertEquals(settingsForCUT.getComponentID(), receivedIdentifyResponse.getFrom());
        assertEquals(identifyRequest.getReplyTo(), receivedIdentifyResponse.getDestination());
        assertEquals(OPERATION_COMPLETED, finalResponse.getResponseInfo().getResponseCode());
        assertEquals(1, finalResponse.getResultingAuditTrails().getAuditTrailEvents().getAuditTrailEvent().size());
    }

    @Test
    @Tag("regressiontest")
    @Tag("pillartest")
    public void checksumPillarGetAuditTrailsSpecificRequests() {
        addDescription("Tests the GetAuditTrails functionality of the pillar for the successful scenario, "
                + "where a specific audit trail are requested.");
        addStep("Set up constants and variables.", "Should not fail here!");
        String auditTrail = "";
        String FILE_ID = "fileID" + new Date().getTime();
        String ACTOR = "ACTOR";
        String INFO = "InFo";
        String AUDITTRAIL = "auditTrails";
        final String OPERATIONID = "operationID";
        final String CERTIFICATEID = "certificateid";
        audits.addAuditEvent(collectionID, FILE_ID, ACTOR, INFO, AUDITTRAIL, OTHER,
                OPERATIONID, CERTIFICATEID);
        audits.addAuditEvent(collectionID, "notThisFile", "UnknownActor", "badInfo", "WrongAuditTrail", FAILURE,
                OPERATIONID, CERTIFICATEID);
        XMLGregorianCalendar minDate = getFromMillis(currentTimeMillis() - 10000);
        XMLGregorianCalendar maxDate = getFromMillis(currentTimeMillis() + 10000);

        addStep("Send the identification request", "Should be caught and handled by the pillar.");
        IdentifyContributorsForGetAuditTrailsRequest identifyRequest =
                msgFactory.createIdentifyContributorsForGetAuditTrailsRequest(auditTrail, getPillarID(),
                        clientDestinationId);
        messageBus.sendMessage(identifyRequest);

        addStep("Retrieve and validate the response.", "Should be a positive response.");
        IdentifyContributorsForGetAuditTrailsResponse identifyResponse = clientReceiver.waitForMessage(
                IdentifyContributorsForGetAuditTrailsResponse.class);
        assertEquals(IDENTIFICATION_POSITIVE, identifyResponse.getResponseInfo().getResponseCode());

        addStep("Make and send the request for the actual GetAuditTrails operation",
                "Should be caught and handled by the pillar.");
        GetAuditTrailsRequest request = msgFactory.createGetAuditTrailsRequest(auditTrail, getComponentID(),
                identifyRequest.getCorrelationID(), FILE_ID, getPillarID(), null, ONE, maxDate,
                ONE, minDate, clientDestinationId, null, pillarDestinationId);
        messageBus.sendMessage(request);

        addStep("Receive and validate the progress response.", "Should be sent by the pillar.");
        GetAuditTrailsProgressResponse progressResponse = clientReceiver.waitForMessage(GetAuditTrailsProgressResponse.class);
        assertEquals(OPERATION_ACCEPTED_PROGRESS, progressResponse.getResponseInfo().getResponseCode());

        addStep("Receive and validate the final response", "Should be sent by the pillar.");
        GetAuditTrailsFinalResponse finalResponse = clientReceiver.waitForMessage(GetAuditTrailsFinalResponse.class);
        assertEquals(OPERATION_COMPLETED, finalResponse.getResponseInfo().getResponseCode());
        assertEquals(1, finalResponse.getResultingAuditTrails().getAuditTrailEvents().getAuditTrailEvent().size());
        AuditTrailEvent event = finalResponse.getResultingAuditTrails().getAuditTrailEvents().getAuditTrailEvent().get(0);
        assertEquals(ACTOR, event.getActorOnFile());
        assertEquals(AUDITTRAIL, event.getAuditTrailInformation());
        assertEquals(FILE_ID, event.getFileID());
        assertEquals(INFO, event.getInfo());
        assertEquals(ONE, event.getSequenceNumber());

        addStep("Make another request, where both ingested audit trails is requested",
                "Should be handled by the pillar.");
        request = msgFactory.createGetAuditTrailsRequest(auditTrail, getComponentID(),
                identifyRequest.getCorrelationID(), null, getPillarID(), null, null, null, null, null, clientDestinationId, null, pillarDestinationId);
        messageBus.sendMessage(request);

        addStep("Receive and validate the progress response.", "Should be sent by the pillar.");
        progressResponse = clientReceiver.waitForMessage(GetAuditTrailsProgressResponse.class);
        assertEquals(OPERATION_ACCEPTED_PROGRESS, progressResponse.getResponseInfo().getResponseCode());

        addStep("Receive and validate the final response", "Should be sent by the pillar.");
        finalResponse = clientReceiver.waitForMessage(GetAuditTrailsFinalResponse.class);
        assertEquals(OPERATION_COMPLETED, finalResponse.getResponseInfo().getResponseCode());
        assertEquals(2, finalResponse.getResultingAuditTrails().getAuditTrailEvents().getAuditTrailEvent().size());
        assertFalse(finalResponse.isPartialResult());
    }

    @Test
    @Tag("regressiontest")
    @Tag("pillartest")
    public void checksumPillarGetAuditTrailsMaximumNumberOfResults() {
        addDescription("Tests the GetAuditTrails functionality of the pillar for the successful scenario, "
                + "where a limited number of audit trails are requested.");
        addStep("Set up constants and variables.", "Should not fail here!");
        final String auditTrail = "";
        final String FILE_ID = "fileID" + new Date().getTime();
        final String ACTOR = "ACTOR";
        final String INFO = "InFo";
        final String AUDITTRAIL = "auditTrails";
        final String OPERATIONID = "operationID";
        final String CERTIFICATEID = "certificateid";
        long maxNumberOfResults = 5L;
        audits.addAuditEvent(collectionID, FILE_ID, ACTOR, INFO, AUDITTRAIL, CHECKSUM_CALCULATED,
                OPERATIONID, CERTIFICATEID);
        audits.addAuditEvent(collectionID, FILE_ID, ACTOR, INFO, AUDITTRAIL, DELETE_FILE,
                OPERATIONID, CERTIFICATEID);
        audits.addAuditEvent(collectionID, FILE_ID, ACTOR, INFO, AUDITTRAIL, FAILURE,
                OPERATIONID, CERTIFICATEID);
        audits.addAuditEvent(collectionID, FILE_ID, ACTOR, INFO, AUDITTRAIL, FILE_MOVED,
                OPERATIONID, CERTIFICATEID);
        audits.addAuditEvent(collectionID, FILE_ID, ACTOR, INFO, AUDITTRAIL, GET_CHECKSUMS,
                OPERATIONID, CERTIFICATEID);
        audits.addAuditEvent(collectionID, FILE_ID, ACTOR, INFO, AUDITTRAIL, GET_FILE,
                OPERATIONID, CERTIFICATEID);
        audits.addAuditEvent(collectionID, FILE_ID, ACTOR, INFO, AUDITTRAIL, GET_FILEID,
                OPERATIONID, CERTIFICATEID);
        audits.addAuditEvent(collectionID, FILE_ID, ACTOR, INFO, AUDITTRAIL, INCONSISTENCY,
                OPERATIONID, CERTIFICATEID);
        audits.addAuditEvent(collectionID, FILE_ID, ACTOR, INFO, AUDITTRAIL, INTEGRITY_CHECK,
                OPERATIONID, CERTIFICATEID);
        audits.addAuditEvent(collectionID, FILE_ID, ACTOR, INFO, AUDITTRAIL, OTHER,
                OPERATIONID, CERTIFICATEID);
        audits.addAuditEvent(collectionID, FILE_ID, ACTOR, INFO, AUDITTRAIL, PUT_FILE,
                OPERATIONID, CERTIFICATEID);
        audits.addAuditEvent(collectionID, FILE_ID, ACTOR, INFO, AUDITTRAIL, REPLACE_FILE,
                OPERATIONID, CERTIFICATEID);

        addStep("Send the request for the limited amount of audit trails to the pillar.",
                "The pillar handles the request and responds.");
        GetAuditTrailsRequest request = msgFactory.createGetAuditTrailsRequest(auditTrail, getComponentID(),
                msgFactory.getNewCorrelationID(), FILE_ID, getPillarID(), valueOf(maxNumberOfResults),
                null, null, null, null, clientDestinationId, null, pillarDestinationId);
        messageBus.sendMessage(request);

        GetAuditTrailsProgressResponse progressResponse = clientReceiver.waitForMessage(GetAuditTrailsProgressResponse.class);
        assertEquals(collectionID, progressResponse.getCollectionID());
        assertEquals(OPERATION_ACCEPTED_PROGRESS, progressResponse.getResponseInfo().getResponseCode());

        addStep("Validate the final response", "Contains OPERATION_COMPLETE, with only the requested amount of audits, "
                + "and acknowledges that it is only a partial result set.");
        GetAuditTrailsFinalResponse finalResponse = clientReceiver.waitForMessage(GetAuditTrailsFinalResponse.class);
        assertEquals(OPERATION_COMPLETED, finalResponse.getResponseInfo().getResponseCode());
        assertEquals(maxNumberOfResults, finalResponse.getResultingAuditTrails().getAuditTrailEvents().getAuditTrailEvent().size());
        assertTrue(finalResponse.isSetPartialResult());
    }
}
