#!/bin/bash

SERVICEURL="http://localhost:8080/bitrepository-webclient-0.0.1-SNAPSHOT/repo/reposervice"
WEBDAVSERVER="http://sandkasse-01.kb.dk/dav/"

do_put() {
	curl --silent -T "$filename" $WEBDAVSERVER > /dev/null
	stripedfilename=`basename $filename`
	filesize=`du -b $filename | cut -f1`
	command="$SERVICEURL/putfile/?fileID=$stripedfilename&url=$WEBDAVSERVER$stripedfilename&fileSize=$filesize"
	curl --silent $command
	echo ""
}

do_getlog() {
	command="$SERVICEURL/getLog/"
	curl --silent $command
}

do_get() {
	command="$SERVICEURL/getfile/?fileID=$filename&url=$WEBDAVSERVER"
	curl --silent $command
	echo ""
}

do_webserver_remove_file() {
	curl --silent -X DELETE $WEBDAVSERVER$filename > /dev/null 
}

do_webserver_get_file() {
	curl --silent $WEBDAVSERVER$filename > $filename
}



case "$1" in
  put)
	filename=$2
	if [ -e $filename ]
	then 
		do_put $filename
	else 
		echo "Usage: br-client put <filename>"	
		return 1
	fi
	;;
  getlog)
	do_getlog;;
  get)
	filename=$2
	if [ -z $filename ]
	then
		echo "Usage br-client get <filename>"
		return 1
	else
		do_get $filename
	fi
	;;
  remove-file)
	filename=$2
	if [ -z $filename ] 
	then
		echo "Usage br-client remove-file <filename>"
		return 1
	else
		do_webserver_remove_file $filename
	fi
	;;
  get-file) 
	filename=$2
	if [ -z $filename ]
	then
		echo "Usage br-client get-file <filename>"
		return 1
	else
		do_webserver_get_file $filename
	fi
esac







