//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-b10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.25 at 02:25:17 PM CEST 
//


package org.bitrepository.protocol;

/**
 * Defines the types of operations in the Bit Repository.
 */
public enum OperationType {
    GET_FILE("GetFile"),
    PUT_FILE("PutFile"),
    DELETE_FILE("DeleteFile"),
    REPLACE_FILE("ReplaceFile"),
    GET_CHECKSUMS("GetChecksums"),
    GET_FILE_IDS("GetFileIDs"),
    GET_AUDIT_TRAILS("GetAuditTrails"),
    ALARMS("Alarms"),
    GET_STATUS("GetStatus");
    private final String value;

    OperationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OperationType fromValue(String v) {
        for (OperationType c: OperationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
